//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Currency_ID { get; set; }
        public int Currency_Gold { get; set; }
        public int Currency_Points { get; set; }
        public int Currency_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
