//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public int Level_ID { get; set; }
        public int Level_NR { get; set; }
        public int Level_Health { get; set; }
        public int Level_Armour { get; set; }
        public int Level_Damage { get; set; }
        public int Level_Stenght { get; set; }
        public int Level_Agility { get; set; }
        public int Level_Dodge { get; set; }
        public int Level_Critical_Chance { get; set; }
        public int Level_Boss { get; set; }
        public int Level_Gold_Min { get; set; }
        public int Level_Gold_Max { get; set; }
        public int Level_Stats_Point { get; set; }
        public int Level_Skill { get; set; }
    }
}
