//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int Stats_ID { get; set; }
        public int Health { get; set; }
        public int Strenght { get; set; }
        public int Agility { get; set; }
        public int Dodge { get; set; }
        public int Critical_Chance { get; set; }
        public int Stats_User { get; set; }
        public int Armour { get; set; }
        public int Damage { get; set; }
    
        public virtual User User { get; set; }
    }
}
