//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grind
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLvl
    {
        public int Level_ID { get; set; }
        public int Level_User { get; set; }
        public int Level_User_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
